### ISSUE TITLE
Error during vdom view: ("unknown zone" (zone America/New_York))

### ISSUE THREAD

**Issue by smondet** [pl-deadlines/pl-deadlines.github.io#1]
Just tried https://pl-deadlines.github.io/

![screenshot-20201205-114543](https://user-images.githubusercontent.com/617111/101258276-713f7580-36ef-11eb-880a-9851c8a301a1.png)

It seems that Jane St's timezone library requires more setup for building with JSOO/web-browser:
https://github.com/janestreet/timezone#web-browsers

**Comment by atrieu** [comment]
Should be fixed by f4ee4f6, can you try again (might need to force refresh on the page) ?
I was already doing the additional setup asked by the library, but it seems like the file produced by the continuous integration doesn't work for your timezone, whereas the one I produce locally on my machine works.

**Comment by smondet** [comment]
It works indeed :+1:
